In [4]:
from IPython.display import Markdown as md

### change to reflect your notebook
_nb_loc = "09_deploying/09d_bytes.ipynb"
_nb_title = "Handling image bytes"

### no need to change any of this
_nb_safeloc = _nb_loc.replace('/', '%2F')
md("""
<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://console.cloud.google.com/ai-platform/notebooks/deploy-notebook?name={1}&url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fpractical-ml-vision-book%2Fblob%2Fmaster%2F{2}&download_url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fpractical-ml-vision-book%2Fraw%2Fmaster%2F{2}">
    <img src="https://raw.githubusercontent.com/GoogleCloudPlatform/practical-ml-vision-book/master/logo-cloud.png"/> Run in AI Platform Notebook</a>
  </td>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/GoogleCloudPlatform/practical-ml-vision-book/blob/master/{0}">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/GoogleCloudPlatform/practical-ml-vision-book/blob/master/{0}">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://raw.githubusercontent.com/GoogleCloudPlatform/practical-ml-vision-book/master/{0}">
    <img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>
""".format(_nb_loc, _nb_title, _nb_safeloc))


<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://console.cloud.google.com/ai-platform/notebooks/deploy-notebook?name=Handling image bytes&url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fpractical-ml-vision-book%2Fblob%2Fmaster%2F09_deploying%2F09d_bytes.ipynb&download_url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fpractical-ml-vision-book%2Fraw%2Fmaster%2F09_deploying%2F09d_bytes.ipynb">
    <img src="https://raw.githubusercontent.com/GoogleCloudPlatform/practical-ml-vision-book/master/logo-cloud.png"/> Run in AI Platform Notebook</a>
  </td>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/GoogleCloudPlatform/practical-ml-vision-book/blob/master/09_deploying/09d_bytes.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/GoogleCloudPlatform/practical-ml-vision-book/blob/master/09_deploying/09d_bytes.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://raw.githubusercontent.com/GoogleCloudPlatform/practical-ml-vision-book/master/09_deploying/09d_bytes.ipynb">
    <img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>


# 画像バイトの処理  

このノートブックでは、(第7章のように)すでにトレーニングされ保存されたモデルのチェックポイントから開始します。  
便宜上、このモデルをgs：//practical-ml-vision-book/flowers_5_trainedのパブリックバケットに配置しました  

私たちがやりたいのは、ネットワークを介してバイトを直接処理することです。そうすれば、クライアントは画像をGoogle CloudStorageに置く必要がなくなります。

## GPUを有効にし、ヘルパー関数を設定します  

このノートブックと、このリポジトリ内の他のほとんどすべてのノートブック  
GPUを使用している場合は、より高速に実行されます。  
Colabについて：  
- [編集]→[ノートブック設定]に移動します  
- [ハードウェアアクセラレータ]ドロップダウンから[GPU]を選択します  

クラウドAIプラットフォームノートブック：  
- https://console.cloud.google.com/ai-platform/notebooksに移動します  
- GPUを使用してインスタンスを作成するか、インスタンスを選択してGPUを追加します  

次に、テンソルフローを使用してGPUに接続できることを確認します。

In [ ]:
import tensorflow as tf
print('TensorFlow version' + tf.version.VERSION)
print('Built with GPU support? ' + ('Yes!' if tf.test.is_built_with_cuda() else 'Noooo!'))
print('There are {} GPUs'.format(len(tf.config.experimental.list_physical_devices("GPU"))))
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
    raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

## チェックポイントから読み取ります。  

署名だけでなく完全なモデルが必要なため、保存されたモデルではなく*チェックポイント*から開始します。

In [3]:
import os
import shutil
import tensorflow as tf

CHECK_POINT_DIR='gs://practical-ml-vision-book/flowers_5_trained/chkpts'
model = tf.keras.models.load_model(CHECK_POINT_DIR)
print(model.summary())

Model: "flower_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
random/center_crop (RandomCr (None, 224, 224, 3)       0         
_________________________________________________________________
random_lr_flip/none (RandomF (None, 224, 224, 3)       0         
_________________________________________________________________
mobilenet_embedding (KerasLa (None, 1280)              2257984   
_________________________________________________________________
dense_hidden (Dense)         (None, 32)                40992     
_________________________________________________________________
flower_prob (Dense)          (None, 5)                 165       
Total params: 2,299,141
Trainable params: 2,265,029
Non-trainable params: 34,112
_________________________________________________________________
None


In [20]:
IMG_HEIGHT = 345
IMG_WIDTH = 345
IMG_CHANNELS = 3
CLASS_NAMES = 'daisy dandelion roses sunflowers tulips'.split()

def read_from_jpegfile(filename):
    img_bytes = tf.io.read_file(filename)
    return img_bytes
    
def preprocess(img_bytes):
    img = tf.image.decode_jpeg(img_bytes, channels=IMG_CHANNELS)
    img = tf.image.convert_image_dtype(img, tf.float32)
    return tf.image.resize_with_pad(img, IMG_HEIGHT, IMG_WIDTH)

In [21]:
filenames = [
    'gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/dandelion/9818247_e2eac18894.jpg',
    'gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/dandelion/9853885425_4a82356f1d_m.jpg',
    'gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/daisy/9299302012_958c70564c_n.jpg',
    'gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/tulips/8733586143_3139db6e9e_n.jpg',
    'gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/tulips/8713397358_0505cc0176_n.jpg'
]
for filename in filenames:
    img_bytes = read_from_jpegfile(filename)
    img = preprocess(img_bytes)
    img = tf.expand_dims(img, axis=0)
    pred = model.predict(img)
    print(pred)

[[0.3507376  0.3983379  0.02309519 0.07595135 0.15187794]]
[[3.1782882e-05 9.9996090e-01 5.1874702e-07 3.2268999e-06 3.5444552e-06]]
[[9.9471879e-01 3.5855272e-03 2.1374140e-05 1.5876008e-03 8.6639280e-05]]
[[1.5454909e-03 2.2907292e-04 3.6099207e-02 3.1195192e-03 9.5900667e-01]]
[[4.7941930e-06 3.9310632e-07 5.8220904e-02 9.1497981e-07 9.4177294e-01]]


## クライアントからのバイトを処理する署名をエクスポートします

In [25]:
@tf.function(input_signature=[tf.TensorSpec([None,], dtype=tf.string)])
def predict_bytes(img_bytes):
    input_images = tf.map_fn(
        preprocess,
        img_bytes,
        fn_output_signature=tf.float32
    )
    batch_pred = model(input_images) # same as model.predict()
    top_prob = tf.math.reduce_max(batch_pred, axis=[1])
    pred_label_index = tf.math.argmax(batch_pred, axis=1)
    pred_label = tf.gather(tf.convert_to_tensor(CLASS_NAMES), pred_label_index)
    return {
        'probability': top_prob,
        'flower_type_int': pred_label_index,
        'flower_type_str': pred_label
    }

@tf.function(input_signature=[tf.TensorSpec([None,], dtype=tf.string)])
def predict_filename(filenames):
    img_bytes = tf.map_fn(
        tf.io.read_file,
        filenames
    )
    result = predict_bytes(img_bytes)
    result['filename'] = filenames
    return result

shutil.rmtree('export', ignore_errors=True)
os.mkdir('export')
model.save('export/flowers_model3',
          signatures={
              'serving_default': predict_filename,
              'from_bytes': predict_bytes
          })

INFO:tensorflow:Assets written to: export/flowers_model3/assets


INFO:tensorflow:Assets written to: export/flowers_model3/assets


In [26]:
!saved_model_cli show --tag_set serve --dir export/flowers_model3

The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "__saved_model_init_op"
SignatureDef key: "from_bytes"
SignatureDef key: "serving_default"


In [27]:
!saved_model_cli show --tag_set serve --dir export/flowers_model3 --signature_def serving_default

The given SavedModel SignatureDef contains the following input(s):
  inputs['filenames'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: serving_default_filenames:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['filename'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: StatefulPartitionedCall_1:0
  outputs['flower_type_int'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: StatefulPartitionedCall_1:1
  outputs['flower_type_str'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: StatefulPartitionedCall_1:2
  outputs['probability'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1)
      name: StatefulPartitionedCall_1:3
Method name is: tensorflow/serving/predict


In [28]:
!saved_model_cli show --tag_set serve --dir export/flowers_model3 --signature_def from_bytes

The given SavedModel SignatureDef contains the following input(s):
  inputs['img_bytes'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: from_bytes_img_bytes:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['flower_type_int'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: StatefulPartitionedCall:0
  outputs['flower_type_str'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: StatefulPartitionedCall:1
  outputs['probability'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1)
      name: StatefulPartitionedCall:2
Method name is: tensorflow/serving/predict


## imgバイトをネットワーク経由で送信する  

GCSに中間ファイルは必要ありません。単にPythonのファイル読み取り方法を使用していることに注意してください。

In [29]:
!gsutil cp gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/daisy/9299302012_958c70564c_n.jpg /tmp/test.jpg

Copying gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/daisy/9299302012_958c70564c_n.jpg...
/ [1 files][ 19.4 KiB/ 19.4 KiB]                                                
Operation completed over 1 objects/19.4 KiB.                                     


In [33]:
with open('/tmp/test.jpg', 'rb') as ifp:
    img_bytes = ifp.read()
    serving_fn = tf.keras.models.load_model('./export/flowers_model3').signatures['from_bytes']
    pred = serving_fn(tf.convert_to_tensor([img_bytes]))
    print(pred)

{'probability': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.9947188], dtype=float32)>, 'flower_type_str': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'daisy'], dtype=object)>, 'flower_type_int': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>}


## バイト処理モデルをCAIPにデプロイします

In [2]:
%%bash
BUCKET="ai-analytics-solutions-mlvisionbook"  # CHANGE
gsutil -m cp -r ./export/flowers_model3 gs://${BUCKET}/flowers_model3

Copying file://./export/flowers_model3/variables/variables.data-00000-of-00001 [Content-Type=application/octet-stream]...
Copying file://./export/flowers_model3/variables/variables.index [Content-Type=application/octet-stream]...
Copying file://./export/flowers_model3/saved_model.pb [Content-Type=application/octet-stream]...
/ [3/3 files][ 10.7 MiB/ 10.7 MiB] 100% Done                                    
Operation completed over 3 objects/10.7 MiB.                                     


In [3]:
%%bash
BUCKET="ai-analytics-solutions-mlvisionbook" # CHANGE
./vertex_deploy.sh \
--endpoint_name=bytes \
--model_name=bytes \
--model_location=gs://${BUCKET}/flowers_model3

Deploying model bytes
Creating bytes endpoint now.
The endpoint_id is 7318683646011899904
Uploading bytes model now.
The model_id is 2990680423643742208
Deploying model now


Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Waiting for operation [1561614649575604224]...
.....done.
Created Vertex AI endpoint: projects/563535018348/locations/us-central1/endpoints/7318683646011899904.
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Waiting for operation [8091834109262823424]...
.....done.
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Using endpoint [https://us-central1-aiplatform.googleapis.com/]
Waiting for operation [3867457658789298176]...
..............................................................................................................................................................................................................................................................................................

## 重要：このセルを変更する  

上記のエンドポイントIDとデプロイされたモデルIDに注意してください。下のセルに設定してください。

In [ ]:
# CHANGE THESE TO REFLECT WHERE YOU DEPLOYED THE MODEL
import os
os.environ['ENDPOINT_ID'] = '7318683646011899904' # CHANGE
os.environ['MODEL_ID'] = '6992243041771716608' # CHANGE
os.environ['PROJECT'] = 'ai-analytics-solutions' # CHANGE
os.environ['BUCKET'] = 'ai-analytics-solutions-mlvisionbook' # CHANGE
os.environ['REGION'] = 'us-central1' # CHANGE

In [43]:
%%bash
gsutil cp gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/daisy/9299302012_958c70564c_n.jpg /tmp/test1.jpg
gsutil cp gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/tulips/8713397358_0505cc0176_n.jpg /tmp/test2.jpg

Copying gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/daisy/9299302012_958c70564c_n.jpg...
/ [1 files][ 19.4 KiB/ 19.4 KiB]                                                
Operation completed over 1 objects/19.4 KiB.                                     
Copying gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/tulips/8713397358_0505cc0176_n.jpg...
/ [1 files][ 34.6 KiB/ 34.6 KiB]                                                
Operation completed over 1 objects/34.6 KiB.                                     


Base64でエンコードされたデータを渡す方法に注意してください

In [8]:
# Invoke from Python.
import base64
import json
from oauth2client.client import GoogleCredentials
import requests

PROJECT = "ai-analytics-solutions"  # CHANGE
REGION = "us-central1"  # make sure you have GPU/TPU quota in this region
ENDPOINT_ID = "7318683646011899904"

def b64encode(filename):
    with open(filename, 'rb') as ifp:
        img_bytes = ifp.read()
        return base64.b64encode(img_bytes)

token = GoogleCredentials.get_application_default().get_access_token().access_token
api = "https://{}-aiplatform.googleapis.com/v1/projects/{}/locations/{}/endpoints/{}:predict".format(
    REGION, PROJECT, REGION, ENDPOINT_ID)
headers = {"Authorization": "Bearer " + token }
data = {
    "signature_name": "from_bytes",  # currently bugged
    "instances": [
        {
            "img_bytes": {"b64": b64encode('/tmp/test1.jpg')}
        },
        {
            "img_bytes": {"b64": b64encode('/tmp/test2.jpg')}
        },
    ]
}
response = requests.post(api, json=data, headers=headers)
print(response.content)

b'{\n  "error": {\n    "code": 400,\n    "message": "Invalid JSON payload received. Unknown name \\"signature_name\\": Cannot find field.",\n    "status": "INVALID_ARGUMENT",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.BadRequest",\n        "fieldViolations": [\n          {\n            "description": "Invalid JSON payload received. Unknown name \\"signature_name\\": Cannot find field."\n          }\n        ]\n      }\n    ]\n  }\n}\n'


## ライセンス  
Copyright 2020 Google Inc. Apache Licenseバージョン2.0(「ライセンス」)に基づいてライセンス供与されます。ライセンスに準拠する場合を除き、このファイルを使用することはできません。ライセンスのコピーはhttp://www.apache.org/licenses/LICENSE-2.0で入手できます。適用法で要求されているか、書面で合意されていない限り、ライセンスに基づいて配布されるソフトウェアは「現状有姿」で配布されます。明示または黙示を問わず、いかなる種類の保証または条件もありません。ライセンスに基づく許可と制限を規定する特定の言語については、ライセンスを参照してください。